linter now outputs warning but doesn't fail

diff --git a/.github/workflows/pr-tests.yml b/.github/workflows/pr-tests.yml
--- a/.github/workflows/pr-tests.yml
+++ b/.github/workflows/pr-tests.yml
@@ -37,4 +37,12 @@ jobs:
         run: pip install -r requirements.txt
 
       - name: Run pylint
-        run: pylint stackhpc_openstack_tests/*.py
+        run: |
+          set +e    # disabling exit on non-zero error code so can output warnings without failing
+          pylint stackhpc_openstack_tests/*.py
+          EXIT_CODE=$?
+          set -e
+          if [[ $(($EXIT_CODE & 3)) > 0 ]]   #bitwise check for pylint exit codes which indicate errors (01 and 10) https://pylint.readthedocs.io/en/latest/user_guide/usage/run.html#exit-codes
+          then
+            exit 1
+          fi
